pull_requests:
  do_not_increment_build_number: false
image: Visual Studio 2019
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  project: DamageEvents.sln
  include_nuget_references: true
  verbosity: minimal
after_build:
  - cmd: copy README.md DamageEvents\bin\Release\net452\README.md
  - cmd: copy LICENSE.md DamageEvents\bin\Release\net452\LICENSE.md
  - cmd: copy fxmanifest.lua DamageEvents\bin\Release\net452\fxmanifest.lua
  - cmd: if %APPVEYOR_REPO_TAG%==true (appveyor SetVariable -Name VERSION_NAME -Value %APPVEYOR_REPO_TAG_NAME%) else (appveyor SetVariable -Name VERSION_NAME -Value beta)
  - cmd: 7z a DamageEvents-%VERSION_NAME%.zip -r DamageEvents\bin\Release\net452\*
  - cmd: appveyor PushArtifact DamageEvents-%VERSION_NAME%.zip
deploy:
  - provider: GitHub
    release: "[Release] DamageEvents $(VERSION_NAME)"
    tag: $(VERSION_NAME)
    artifact: DamageEvents-$(VERSION_NAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      APPVEYOR_REPO_TAG: true
    description: "Damage Events version $(VERSION_NAME)."
